[build]
  command = "npm install && npm run build && node copy-optimized-assets.js"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200