services:
  - type: web
    name: softworks-trading
    buildCommand: npm install --no-audit --no-fund && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: API_TIMEOUT
        value: 30000
      - key: SESSION_SECRET
        sync: false
      - key: CSRF_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://www.softworkstrading.com
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ELEVENLABS_DEFAULT_VOICE_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=3600, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: max-age=31536000, immutable
      - path: /optimized-images/*
        name: Cache-Control
        value: max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /blog
        destination: /blog/index.html
      - type: rewrite
        source: /*
        destination: /index.html

# Additional render.yaml configuration
headers:
  # Security headers for all routes
  "/*":
    # HSTS is a security feature that tells browsers that the site should only be accessed over HTTPS
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    # Prevent MIME type sniffing, which can lead to security vulnerabilities
    X-Content-Type-Options: nosniff
    # Prevents the browser from rendering the page inside a frame/iframe
    X-Frame-Options: DENY
    # Enables XSS filtering in browsers
    X-XSS-Protection: 1; mode=block
    # Controls how much referrer information should be included with requests
    Referrer-Policy: strict-origin-when-cross-origin