services:
  - type: web
    name: softworks-trading
    env: node
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 18.20.7
    envVars:
      - key: NODE_ENV
        value: production
    plan: free # Start with free plan