services:
  - type: web
    name: softworks-trading
    env: node
    runtime: node
    nodeVersion: 18.20.7
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    plan: starter # Using the $7/month paid plan