services:
  - type: web
    name: softworks-trading
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    plan: starter # Using the $7/month paid plan